apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: roletask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sadokaziz/roletask-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8094
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/roletask_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root_password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SERVER_PORT
              value: "8094"
            - name: JWT_SECRET
              value: roletask_secret_key_2026_change_me